### ISSUE TITLE
Mysensors binding [channel names disappearing in paperui control page after OH2 restart]

### ISSUE THREAD

**Issue by rocket59** [tobof/openhab2-addons#102] opened 2017-11-06 00:03 UTC
Openhab 2.2 installed via apt (raspbian jessie)
Mysensors binding installed via IOT marketplace (market:binding-3328323 - 1.0)

Possible bug is as described here:
https://community.openhab.org/t/mysensors-binding-channel-names-disappearing-in-paperui-control-page-after-reboot/35706

Workaround is given in the 2nd post of the above thread.

**Comment by rocket59** [comment] 2017-11-16 06:40
Note: potential solution is posted towards the end of the thread by a contributor.

**Comment by tobof** [comment] 2018-01-10 09:27
I'm not able to reproduce this error with the current code base. I suppose it was fixed with an update for OpenHAB2.

**Closed by tobof** 2018-01-10 09:27 UTC
Labels: bug
