### ISSUE TITLE
Updates stops after OpenHAB offline

### ISSUE THREAD

**Issue by antonholmstedt** [tobof/openhab2-addons#77] opened 2017-04-19 06:33 UTC
When I woke up I had received two notifications, OpenHAB offline 02:20 and back online 02:21. Since then, my first and only mysensors sensor, outdoor temperature, has stopped updating. The last update was received at 02:20. When I had this problem last time, a restart of the Rpi solved the problem.

I'm running OpenHAB on a Rpi rev2 + (512mb), and an esp8266 as mysensors gw. The temperature sensor runs of AC and updates temperature on every change. In paperui the gw is still marked as Online.

Will update with log when I get home.

**Comment by andreacioni** [comment] 2017-04-21 21:03
Hi @antonholmstedt , thanks for reporting. I don't understand what is going on in your system. I hope log file will tell us more about your problem

**Comment by tobof** [comment] 2017-06-14 05:53
@antonholmstedt We need the log to help you. I will close this issue. Feel free to attach the log if the problem is still there and I will reopen the issue.

**Closed by tobof** 2017-06-14 05:53 UTC
